spring.application.name=MartaTransportationTracker

marta.api.key=${MARTA_API_KEY_0}

marta.http.connect-timeout-ms=2000
marta.http.read-timeout-ms=5000

marta.retry.max-attempts=3
marta.retry.initial-delay-ms=500
marta.retry.multiplier=2.0
marta.retry.max-delay-ms=4000

